apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- insecure_api_enpoint.yaml
images:
- name: dhub.c2.croc.ru/kaas/aws-ebs-csi-driver
  newName: dhub.c2.croc.ru/aleksefimov/aws-ebs-csi-driver
  newTag: latest
